kind: Deployment
apiVersion: apps/v1
metadata:
  name: cli-tools
  namespace: buildconfig-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cli-tools
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cli-tools
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/buildconfig-example/cli-tools
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
